namespace: canary-dev

serviceA:
  image: localhost:5000/service-a
  tag: v1
  port: 8080
  replicas: 2

serviceB:
  image: localhost:5000/service-b
  tag: v1
  port: 8081
  replicas: 2

canary:
  enabled: true
  steps:
    - setWeight: 10
    - pause: { duration: 1m }
    - setWeight: 30
    - pause: { duration: 1m }
    - setWeight: 50
    - pause: { duration: 1m }
    - setWeight: 100
