apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-service-a-dr
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Release.Name }}-service-a-stable
  subsets:
  - name: stable
    labels:
      app: service-a
  - name: canary
    labels:
      app: service-a
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-service-b-dr
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Release.Name }}-service-b-stable
  subsets:
  - name: stable
    labels:
      app: service-b
  - name: canary
    labels:
      app: service-b
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
