apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-service-a-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - service-a
  http:
  - name: http
    route:
    - destination:
        host: {{ .Release.Name }}-service-a-stable
        subset: stable
      weight: 100
    - destination:
        host: {{ .Release.Name }}-service-a-canary
        subset: canary
      weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-service-b-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - service-b
  http:
  - name: http
    route:
    - destination:
        host: {{ .Release.Name }}-service-b-stable
        subset: stable
      weight: 100
    - destination:
        host: {{ .Release.Name }}-service-b-canary
        subset: canary
      weight: 0
